#pragma once

typedef enum
{
	CMD_JOIN,
	CMD_JOIN_ACK,
	CMD_LIST_USERS,
	CMD_LIST_USERS_ACK,
	CMD_EXIT_ROOM,
	CMD_EXIT_ROOM_ACK,
		
} COMMAND_TYPE;

char *arrCmd[] = {"CMD_JOIN", "CMD_JOIN_ACK", "CMD_LIST_USERS", "CMD_LIST_USERS_ACK", \
				"CMD_EXIT_ROOM", "CMD_EXIT_ROOM_ACK", NULL};

